### ISSUE TITLE
Please add data.table

### ISSUE THREAD

**Issue by leofontenelle** [dvdesolve/ArchRPkgs#11]
Could you please also add [`data.table`](https://cran.r-project.org/package=data.table) to the repository? The package is easy enough to install from within R, but needs compilation and is imported by gazillions of other package, so I guess it's a good one to add.

**Comment by dvdesolve** [comment]
hmm, it's quite interesting. I've always thought that it is already in this repo. thank you for pointing that out!

**Comment by dvdesolve** [comment]
Just rechecked - it's already in the repo
