### ISSUE TITLE
r-rncep package

### ISSUE THREAD

**Issue by Vokhirion** [dvdesolve/ArchRPkgs#14]
Hello, I'm trying to install package [RNCEP](https://cran.r-project.org/package=RNCEP) on Rstudio but I cant fix “tcl/tk support is not available on this system” & “non-zero exit status” errors. When this error occurs on other package installations, I used your repo to install that packages and they perfectly worked. How can I write a pkgbuild like yours or is there any solution that you can recommend please?

**Comment by dvdesolve** [comment]
I have no RNCEP package in this repo. What do you mean when you talk about `to install that packages`?
