### ISSUE TITLE
Codependent packages: r-httpuv and r-websocket

### ISSUE THREAD

**Issue by alhirzel** [dvdesolve/ArchRPkgs#18]
When trying to install `r-markbook`, I noted that `r-httpuv` and `r-websocket` are codependent because they are listed in each others' `check` dependency list. I also see that they each list the other as "optional". Perhaps this *should* hint to the helper I am using ([`yay`](https://github.com/Jguer/yay)) that this loop can be broken? I have resolved this for now by arbitrarily installing one before the other with `--nocheck`, but want to bring this to your attention since you are more experienced with R PKGBUILDs and `r-httpuv` is under your control.

**Comment by dvdesolve** [comment]
thank you for pointing that out. where you have found them in `checkdepends` array? I don't use `check()` step in all of R PKGBUILDs

**Comment by dvdesolve** [comment]
Seems like similar to #17
