### ISSUE TITLE
r-backports is outdated

### ISSUE THREAD

**Issue by mschrumpf** [dvdesolve/ArchRPkgs#2]
I have encountered an error where the download for r-backports keeps failing. The reason seems to be that a new version of that package (1.4.1) is available from cran.r-project.org. The older version (1.4.0) has been moved to the archive using a different URL. 
This error also makes it impossible to install r-tidyverse using pacman since r-backports is a dependency of that package. 
I would appreciate it if the package could be updated with the appropriate URL or the most recent version of the package.

**Comment by dvdesolve** [comment]
hello! I've been waiting for the first issue of such kind. Inevitably some of provided R packages will go out of date sometime so fixes to PKGBUILDs will be necessary (and reuploading too). my proposal is to use issues mechanism to keep me notified when some package becomes outdated. we can close them as update will be done and re-open if new update is needed. there is also convenient tool shipped with this repo which facilitates checking for updates for current packages

regarding the subject itself - I'll take a look in short time
