### ISSUE TITLE
Cannot install pandoc-dependent packages

### ISSUE THREAD

**Issue by AlexBocken** [dvdesolve/ArchRPkgs#20]
With the recent move of `pandoc` to `community/pandoc-cli` this breaks the version checks employed in a few PKBUILDs.

pandoc-cli includes a `provides("pandoc")`, but I think it's the explicit version checking that's breaking the install for now.

For me two packages are not installing `r-rmarkdown` and `r-reprex`.

**Comment by dvdesolve** [comment]
Fixed in [914d4ea](https://github.com/dvdesolve/ArchRPkgs/commit/914d4ea77d7e9572b35ee9ea3c9981af359fd201)
