### ISSUE TITLE
r-stringi requires a rebuild against new icu

### ISSUE THREAD

**Issue by AlexBocken** [dvdesolve/ArchRPkgs#22]
Heyo, I stumbled into an issue with r-stringi. Seems like the current release is built against an older version of icu and cannot find the new libraries.
Could you bump the pkgrel to fix this?
Installing the r-stringi package from the AUR works without any issues.

Here's the current output if I try to install an r package which is dependent on r-stringi:
```
[...]
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/lib/R/library/stringi/libs/stringi.so':
  libicui18n.so.73: cannot open shared object file: No such file or directory
Calls: <Anonymous> ... namespaceImport -> loadNamespace -> library.dynam -> dyn.load
Execution halted
```

Also, I noticed that it's a bit out-of date. Any reason for this or could we also just bump the pkgver to the current release?

**Comment by TimoStolz** [comment]
Exactly the same here. It's not just during installation. I already had it installed. It breaks when being imported, too. I got it working with `yay -S aur/r-stringi`.
