### ISSUE TITLE
r-httpuv is outdated

### ISSUE THREAD

**Issue by BirdDev** [dvdesolve/ArchRPkgs#3]
Hi, I cannot download the httpuv version **1.6.4**:
`curl: (22) The requested URL returned error: 404
==> ERROR: Failure while downloading https://cran.r-project.org/src/contrib/httpuv_1.6.4.tar.gz`
and in `https://cran.r-project.org/src/contrib/` there is only httpuv version **1.6.5** so I wanted to let you know according to #2 

Also, I get the same result with `r-fansi`, should I open a new issue for that one, too?

Thank you very much in advance :)

**Comment by dvdesolve** [comment]
`r-httpuv` was updated in one of the previous commits :) However, I've just updated fansi, rcpp and jsonlite in 13a5192
Thank you for keep it going!
