### ISSUE TITLE
r-jsonlite is outdated

### ISSUE THREAD

**Issue by gnaggnoyil** [dvdesolve/ArchRPkgs#4]
`aur/r-jsonlite` had already been marked as outdated, with the following reason:

```
does not build (404 in download), cran has 1.8.0
```

I tried PKGBUILD in bf6b901 and the result was the same.

BTW the optional dependency `r-r.rsp` does not appear in aur nor in this repo. Where did that package go?

**Comment by dvdesolve** [comment]
IIRC there were some problems with r-r.rsp package
