### ISSUE TITLE
r-cli is outdated

### ISSUE THREAD

**Issue by japhir** [dvdesolve/ArchRPkgs#5]
https://cran.r-project.org/package=cli says that 3.2.0 is out!

Do you have a script or something to automatically check if packages are outdated?

**Comment by japhir** [comment]
Same for:
- r-generics (0.1.2)
- r-magrittr
- r-rlang

**Comment by dvdesolve** [comment]
Thank you for letting me know! I'll try to find some time and update packages ASAP

**Comment by japhir** [comment]
I think I still have some AUR packages installed, and now pacman is complaining that your repo has older versions than the AUR packages:
![2022-04-19-14:06:48_region](https://user-images.githubusercontent.com/10659193/163999817-a40a434e-e249-4e95-93f3-ca0bb6ebac91.png)

Also, since today brought a new version of R, we need to rebuild r-stringi, so your binary also needs to be recompiled

**Comment by japhir** [comment]
Nice, thank you very much! :)

I obsessively run `paru`, usually more than once a day meaning I'm usually an early-noticer of issues. I hope you find them helpful rather than annoying.

**Comment by dvdesolve** [comment]
of course, that's how this mechanism should work

I just have some hard times now but things are going to fix so I will be in the game soon again:)

**Comment by japhir** [comment]
hope things get better soon!  👍🏽
