### ISSUE TITLE
Trying to install r-httpuv, but keep getting missing dependency 

### ISSUE THREAD

**Issue by zmvmarina** [dvdesolve/ArchRPkgs#6]
This is what I get after I run

 `pamac build r-httpuv`

> Building r-webutils...
> ==> Making package: r-webutils 1.1-1 (Sun **************************)
> ==> Checking runtime dependencies...
> ==> Missing dependencies:
>   -> r-curl
> ==> Checking buildtime dependencies...
> ==> Missing dependencies:
>   -> r-httpuv
> ==> ERROR: Could not resolve all dependencies.

Any idea how to resolve this issue? I have attempted to build all above mentioned dependencies separately, but get the same error with packages mentioned in a different order

Thank you!

**Comment by dvdesolve** [comment]
it's strange because `r-curl` is in this repo. It's possible that some of the packages are outdated - I'll try to find some time to fix things soon.
As for now try to manually build `r-curl` with `makepkg` directly and then install it by `pacman -U package_tarball`

**Comment by dvdesolve** [comment]
seems like you're installing packages from aur and not from this repo
try to add my repository and install necessary packages via pacman directly
