### ISSUE TITLE
Feature request r-gstat

### ISSUE THREAD

**Issue by carlosal1015** [dvdesolve/ArchRPkgs#7]
Hi @dvdesolve I hope you stay well. Well I am writing because I would like to ask if is possible to help me or maybe for you is interesting to maintain r-gstat. There is no available from AUR. What do you think?	I am reading the [R package guidelines](https://wiki.archlinux.org/title/R_package_guidelines), but is not too clear to me or I could do mistakes in the process. Is necessary to recompile like python when R is newer?

```
➜  ~ yay -Ss gstat
aur/tgstation-server-controlpanel-git r221.e0f1033-1 (+0 0.00) 
    Official client for tgstation-server v4
aur/gstatz 1.3-3 (+1 0.00) 
    utility for tracking cycles of menstruation and for prediction of next period's date
aur/dockingstation 195-1 (+2 0.00) (Out-of-date: 2022-03-02) 
    Artificial life game based on Creatures 3
aur/escribe-suite-bin 2_SP31-1 (+5 0.06) 
    Evolv eScribe Suite - DNA Management Suite and Ecigstats - INTL Version
extra/pkgstats 3.2.1-1 (2.3 MiB 6.9 MiB) (Installed)
    Submit a list of installed packages to the Arch Linux project
```

Debian, Ubuntu, NixOS have this package in the official repositories, but Arch Linux no. Maybe could be r-gstat-git too.

- [Repology](https://repology.org/projects/g/?search=gstat)
- Source: https://github.com/r-spatial/gstat
- http://gstat.org

Thank you.

**Comment by dvdesolve** [comment]
Hello! I'll take a look soon and add it to the repo

**Comment by carlosal1015** [comment]
Thank you very much, I maintain recently your past packages
- [`r-viridis`](https://aur.archlinux.org/packages/r-viridis)
- [`r-rgdal`](https://aur.archlinux.org/packages/r-rgdal)
- [`r-move`](https://aur.archlinux.org/packages/r-move)
- [`r-metr`](https://aur.archlinux.org/packages/r-metr)

Not sure if [`gstat`](https://gitlab.com/dune-archiso/pkgbuilds/dune/-/blob/main/PKGBUILDS/gstat/PKGBUILD) is a dependency.

Thanks in advance.
