### ISSUE TITLE
key out of date?

### ISSUE THREAD

**Issue by japhir** [dvdesolve/ArchRPkgs#9]
when updating I get: "signature from "Viktor Drobot <linux776@gmail.com>" is unknown trust"

and when I try to pacman-key --recv-keys your_key I get 
```
gpg: keyserver receive failed: Server indicated a failure
==> ERROR: Remote key not fetched correctly from keyserver.
```

**Comment by dvdesolve** [comment]
You should try to specify another keyserver by hand. Try with Ubuntu's one
